// <auto-generated />
using System;
using ComponentsUtil.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComponentsUtil.Persistence.Migrations
{
    [DbContext(typeof(TestTaskContext))]
    partial class TestTaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComponentsUtil.Persistence.Entities.Detail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("DetailId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            DetailId = 1,
                            Name = "Engine #234"
                        },
                        new
                        {
                            DetailId = 2,
                            Name = "Engine #456"
                        },
                        new
                        {
                            DetailId = 3,
                            Name = "Crankshaft"
                        },
                        new
                        {
                            DetailId = 4,
                            Name = "Camshaft"
                        },
                        new
                        {
                            DetailId = 5,
                            Name = "Piston assembly"
                        },
                        new
                        {
                            DetailId = 6,
                            Name = "Piston"
                        },
                        new
                        {
                            DetailId = 7,
                            Name = "Compression ring"
                        },
                        new
                        {
                            DetailId = 8,
                            Name = "Oil scrapper ring"
                        },
                        new
                        {
                            DetailId = 9,
                            Name = "Connecting rod"
                        },
                        new
                        {
                            DetailId = 10,
                            Name = "Cylinder block"
                        });
                });

            modelBuilder.Entity("ComponentsUtil.Persistence.Entities.DetailRelation", b =>
                {
                    b.Property<int>("DetailRelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<int>("DetailId")
                        .HasColumnType("int");

                    b.Property<HierarchyId>("HierarchyId")
                        .IsRequired()
                        .HasColumnType("hierarchyId");

                    b.HasKey("DetailRelationId");

                    b.HasIndex("DetailId");

                    b.HasIndex("HierarchyId")
                        .IsUnique()
                        .HasName("RelationHierarchyUnique")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("DetailRelations");

                    b.HasData(
                        new
                        {
                            DetailRelationId = 1,
                            DetailId = 1,
                            HierarchyId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/")
                        },
                        new
                        {
                            DetailRelationId = 2,
                            DetailId = 2,
                            HierarchyId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/2/")
                        },
                        new
                        {
                            DetailRelationId = 3,
                            Count = 1,
                            DetailId = 10,
                            HierarchyId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/10/")
                        },
                        new
                        {
                            DetailRelationId = 4,
                            Count = 1,
                            DetailId = 3,
                            HierarchyId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/")
                        },
                        new
                        {
                            DetailRelationId = 5,
                            Count = 2,
                            DetailId = 4,
                            HierarchyId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/")
                        },
                        new
                        {
                            DetailRelationId = 6,
                            Count = 4,
                            DetailId = 5,
                            HierarchyId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/")
                        },
                        new
                        {
                            DetailRelationId = 7,
                            Count = 1,
                            DetailId = 6,
                            HierarchyId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/6/")
                        },
                        new
                        {
                            DetailRelationId = 8,
                            Count = 2,
                            DetailId = 7,
                            HierarchyId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/7/")
                        },
                        new
                        {
                            DetailRelationId = 9,
                            Count = 1,
                            DetailId = 8,
                            HierarchyId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/8/")
                        },
                        new
                        {
                            DetailRelationId = 10,
                            Count = 4,
                            DetailId = 9,
                            HierarchyId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/9/")
                        });
                });

            modelBuilder.Entity("ComponentsUtil.Persistence.Entities.DetailRelation", b =>
                {
                    b.HasOne("ComponentsUtil.Persistence.Entities.Detail", "Detail")
                        .WithMany("DetailRelations")
                        .HasForeignKey("DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
